### ISSUE TITLE
アニメーション作成ウィンドウでリップシンクで使われているブレンドシェイプが一覧に表示される

### ISSUE THREAD

**Issue by c-colloid** [suzuryg/face-emo#10]
リップシンクに使われているブレンドシェイプはアニメーション内で使用してしまうと表情が固まってしまうが問題があります
現状では他のブレンドシェイプと並んで表示されているため間違って触ってしまう可能性があります
間違って入れてしまった場合に警告表示が出てはいますが、Unityをよくわかってない人はそれも無視される可能性があると思います

カテゴリー分けするか、普段は非表示でオプションで表示されるようにするか等で初心者が間違って触ってしまわないような処置が必要だと思います

**Comment by suzuryg** [comment]
提案ありがとうございます。たしかに警告無視の可能性はありますね。
（まばたきはともかく）リップシンク用ブレンドシェイプを有効に使える可能性はほぼないので、インスペクタにオプション追加しようかと思います。
