### ISSUE TITLE
MA Scale Adjusterのコンポーネントを使用した場合にプレビューが機能しない

### ISSUE THREAD

**Issue by yukipod** [suzuryg/face-emo#124]
コンポーネントにMA Scale Adjusterを使用している場合、FaceEmoの表情プレビューが動作しません。
バージョン:1.5.3
MAバージョン:1.9.4

画像1: コンポーネントあり
![image](https://github.com/suzuryg/face-emo/assets/12232795/535479aa-8dcd-44d4-bdbd-b9dfc63cf6cf)
画像2: コンポーネントなし
![image](https://github.com/suzuryg/face-emo/assets/12232795/fee02f62-3fc4-4046-9f86-b0c87df539d7)

**Comment by suzuryg** [comment]
報告ありがとうございます。対応方法について検討中ですので、少々お待ちください。

**Comment by yukipod** [comment]
御対応ありがとうございます。
上記件、MA側のバージョンアップによってプレビュー機能が正常に動作したことを確認しました。
バージョン:1.5.3
MAバージョン:1.9.6
