### ISSUE TITLE
FaceEmoPrefab removed from Launcher on reload, grayed out

### ISSUE THREAD

**Issue by ArkorenSnep** [suzuryg/face-emo#125]
![image](https://github.com/suzuryg/face-emo/assets/65946087/8dbd6769-c7c0-46e3-9c73-f281f3642fbb)

After applying FaceEmo to an avatar this box correctly contains the prefab, but when I reload the scene or project the prefab is no longer selected and it's grayed out like in the above image. Since the prefab is removed and I can't select the prefab to be updated, it's always generating a new prefab and replacing it when I want it to be updating the existing one. This makes it very difficult to update the avatars in my other scenes.

Maybe I'm just doing it wrong or missing a setting, but I've looked through the documentation multiple times and can't find a way to fix it.

**Comment by suzuryg** [comment]
Thanks for the report. I have confirmed the problem is reproduced in my environment as well. I will fix it in the next release.
