### ISSUE TITLE
VRCHierarchyHighlighterと競合する

### ISSUE THREAD

**Issue by Narazaka** [suzuryg/face-emo#13]
FaceEmoのインストールによって、アイコンでの情報表示が便利な下記アセットVRCHierarchyHighlighterの表示がなされなくなります。
https://github.com/AzuriteLab/VRCHierarchyHighlighter

ヒエラルキーの表示に不干渉にするオプションなどが欲しいです。

FaceEmoをインストールした場合
![image](https://github.com/suzuryg/face-emo/assets/1712548/204cec80-0584-48f7-978a-f78697a839e9)
FaceEmoをアンインストールした場合
![image](https://github.com/suzuryg/face-emo/assets/1712548/6b32766d-4d9a-4f9c-9e32-9ed8f29ef368)

**Comment by Narazaka** [comment]
VRCHierarchyHighlighterと競合しない場合もある模様。（再インストールした。初回インストール時にコンパイルエラーが出てから直していた。）
![image](https://github.com/suzuryg/face-emo/assets/1712548/7a61caa3-6200-446c-8154-bb2b5064466d)

**Comment by c-colloid** [comment]
類似ツールのHierarchyProの場合、競合はしないんですが表示がかぶってしまいボタンが押せなくなるので、
表示位置を調整するオプションがあると嬉しいです
![image](https://github.com/suzuryg/face-emo/assets/28706700/86a66c2d-edfb-467e-a6cb-5d507db35df1)

**Comment by suzuryg** [comment]
@Narazaka 
VRCHierarchyHighlighterのコンパイル失敗がFaceEmo起因でなければ問題ない気がします。再現条件わかりますか？
表示が重なることはありますが、他のヒエラルキー表示に干渉することはないはず…

@c-colloid 
なにかしらの改善が必要かとは思いますが、オプション追加が妥当かどうかは悩ましいです。
（起動して最初に押す想定のボタンなので）
とはいえすべてのヒエラルキー系ツールに対応するのも難しいですが…

**Comment by Narazaka** [comment]
コンパイルエラーは一応FaceEmo起因で、Packages/の下もgit管理する（.gitignoreを削除してコミットする）方式をとっていたが、下位の.gitignoreに気づかずコミットし、別プロジェクトでpullったときにファイルが足りなくて起こったものです。
通常起こらない事象だと思います。

**Comment by Narazaka** [comment]
あえてEmoボタンが必要となるのは基本的にはUnityに慣れていない人々だと思います。
ヒエラルキー系ツールを使うのはパワーユーザー寄りだと思うので、そのようなケースに対してオプションを設けるのは別に妥当な気はします（実装コスパとしては悪そう）。

**Comment by suzuryg** [comment]
@Narazaka 
発生要因について了解です。だいぶレアケースなのと、考えつく限り他のヒエラルキー表示に影響する処理は入れていないはずなので、これについては対処不要だと思っています。

Emoボタンはこちらも初心者想定で入れていました。
広く使われている VRCHierarchyHighlighter には対応しているのと、他のツールを使うパワーユーザーはEmoボタン非表示で対処できることを考えると、オプション実装の優先度はだいぶ低いですね…

**Comment by c-colloid** [comment]
私も今は Emoボタン非表示で対処してますので正直な所このままでも問題ない状態ではあります
ですので至急に対応していただく必要はありません

ですが、Hierarchy上のボタンで起動できるというのはオブジェクトの選択を変えずに作業を続けられるという点で、作業時のストレスを下げられる為とても魅力があるので、将来的に実装を考えてくれると嬉しいです

（ちなみにいうと HierarchyPro は VRCHierarchyHighlighter が出る前に最も紹介されていた Hierarchy拡張なのでSDK2時代からプレイしているコアユーザーなら結構持ってる人は多いのではないかと思います）
