### ISSUE TITLE
Face Expression seemed to be reset when doing the AFK Outro

### ISSUE THREAD

**Issue by blufish1234** [suzuryg/face-emo#42]
I disabled AFK Face in the FaceEmo to use the original AFK expression. However, I discovered that there are no face expressions when the AFK during outro. 
Also, bypassing FaceEmo when selected FX Parameters has been changed would be a good idea. Since there are some face expressions that depends on Parameter changes (Such as pulling the tail or ear).

**Comment by suzuryg** [comment]
I had not noticed that the outro expression is overwritten. Thanks for reporting this!
However, it seems difficult to properly bypass the animation after the AFK variable is set to false.
(It is not possible to make a state transition after the outro animation has finished playing).
I think the compromise is to use FaceEmo's AFK face setting if the outro animation is a concern...

**Comment by blufish1234** [comment]
Maybe it is possible to determine the length of the outro animation and stop bypassing when the animation ends?

**Comment by suzuryg** [comment]
I see. If the transition time is not determined from existing AFK states or animations, but added as a set value, it can be implemented.
