### ISSUE TITLE
hai Animation Viewerと相性が悪い

### ISSUE THREAD

**Issue by Narazaka** [suzuryg/face-emo#70]
Animation Viewerはプロジェクト上のアニメーションファイルをサムネイル表示できるツールですが、これがFaceEmoを開いている間正しくプレビューが出ない状態になります。
https://hai-vr.booth.pm/items/3625699

**Comment by suzuryg** [comment]
FaceEmo 1.3.1で確認しましたが、正しくサムネイルを描画できています。
どのような環境で、どのような不具合が発生していますか？
![スクリーンショット 2023-11-06 220113](https://github.com/suzuryg/face-emo/assets/77635213/bffd9d7d-bcc7-4b39-b0e2-a96f4f2e75a2)

**Comment by Narazaka** [comment]
FaceEmoのアニメーション編集ツールを開いている状態で、サムネが更新された時にっぽいです

**Comment by suzuryg** [comment]
再現しました。
Animation Viewerはサムネイル更新の際に SceneView.lastActiveSceneView を参照しているのですが、FaceEmoの表情エディタを使用している間は lastActiveSceneView がFaceEmoのウインドウになり、skyboxが描画されます。

lastActiveSceneView はget-only となっており、少なくとも公開APIからは変更できないようです。
（コードからウインドウのフォーカス状態を変更しても lastActiveSceneView は変更されず、ビューをクリックした場合のみ変更される）

Sceneビューをクリックすると Animation Viewer のサムネイル描画が正常化されるので、ひとまずその方法での回避をお願いします…
