### ISSUE TITLE
NDMFとFaceEmoでpackage.jsonやEditorとGUIDがかぶっています

### ISSUE THREAD

**Issue by Narazaka** [suzuryg/face-emo#76]
恐らくテンプレートリポジトリそのままの物を使っているからかと？
![image](https://github.com/suzuryg/face-emo/assets/1712548/8ad184c6-5d04-4e95-8eb6-6172e2aeaf56)

**Comment by suzuryg** [comment]
報告ありがとうございます！修正しました。#79
