### ISSUE TITLE
Bone Proxyで髪の毛移植するとプレビュー画面で正しく表示されない

### ISSUE THREAD

**Issue by bdunderscore** [suzuryg/face-emo#90]
![image](https://github.com/suzuryg/face-emo/assets/64174065/38ce9ac5-5b1c-4724-8180-9d0fc57c96a9)

このアバターでは、髪の毛をModular AvatarのBone Proxyで配置していますが、プレビュー画面で位置がずれます。

**Comment by bdunderscore** [comment]
[Lime Variant.zip](https://github.com/suzuryg/face-emo/files/13658374/Lime.Variant.zip)

LimeとManukaを両方導入することで再現できるプレハブです。

**Comment by bdunderscore** [comment]
1.4.4で直っていたのでクローズします。

**Comment by suzuryg** [comment]
報告ありがとうございます！修正しました。
